---

name: "Repository CI"


on:
  push:
    paths:
      - "**.yaml"
  pull_request:
    paths:
      - "**.yaml"
  workflow_dispatch:


jobs:
  call-pre-commit:
    name: "Call reusable pre-commit workflow"
    uses: ./.github/workflows/pre-commit.yaml
