---

name: "PlatformIO build workflow"
author: "ravngr"
description: "Execute a build using PlatofrmIO and optionally upload produced artefacts"


on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python environment version'
        default: '3.11'
        required: false
        type: string

      pio-environment:
        description: 'PlatformIO environment name'
        required: true
        type: string


jobs:
  pio-build:
    name: "Build firmware using PlatformIO"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python-version }}"
          cache: 'pip'

      - name: "Setup PlatformIO"
        run: |
          pip install platformio

      - name: "Run build"
        run: |
          pio run -e "${{ inputs.pio-environment }}"
