---

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python environment version'
        default: '3.11'
        required: false
        type: string


jobs:
  pre-commit:
    name: "Run pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python-version }}"

      - name: "Install pre-commit"
        run: |
          pip install pre-commit

      - name: "Cache pre-commit environment"
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit_${{ env.pythonLocation }}_${{ hashFiles('.pre-commit-config.yaml') }}

      - name: "Run all pre-commit tests"
        run: |
          pre-commit run -a --color=always
