---

name: "yamllint workflow"


on:
  workflow_call:


jobs:
  lint:
    name: "Lint YAML files using yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3

      - name: "Run yamllint"
        uses: ibiqlik/action-yamllint@v3
